### ISSUE TITLE
Generated code and enum deserialisation

### ISSUE THREAD

**Issue by RichardCubic** [XeroAPI/Xero-NetStandard#201] opened 2020-07-30 10:44 UTC
There have been a few issues where the introduction of new enum values have caused problems in the C# SDK (eg #200, #131)

Ultimately, the problem is in the fact that the generated code is deserialising enums using the StringEnumConverter, which is utterly intolerant of unknown values. This means that any updates to the enum contents will cause exceptions for anyone who's not absolutely bang up-to-date.

Introducing something like the TolerantEnumConverter at https://stackoverflow.com/a/22755077 and adjusting the code generation accordingly would stop this whole class of issue.

**Comment by jenksguo** [comment] 2020-07-31 05:41
Hi @RichardCubic, that is a good analysis of the most of the issues. 

We rely on the manually maintained OpenAPI spec and ENUMs to get out of sync as API products start to change. 

Thanks for the suggestion, we will look into this as an improvement.

**Comment by jenksguo** [comment] 2020-09-13 10:40
Hi @RichardCubic, thanks for your suggestion. This is still in discussion internally just to let you know.

**Comment by jenksguo** [comment] 2020-10-18 06:32
Still in discussion. We will be updating the ENUM more frequently and ahead of product changes.

**Comment by jenksguo** [comment] 2020-11-12 05:03
Hi @RichardCubic, thanks for your recommendation. 

We have decided not to implement this for this year. But we have improved our internal processed between teams to get ENUM changes into our SDKs ahead of product releases. So similar issue is less likely.

**Comment by jenksguo** [comment] 2020-12-14 05:40
Hi @RichardCubic, the issue is on our backlog, but we won't be able to add to it until some time later this year. The structural change will require us to re-assess the openapi generation templates thoroughly.  Would you mind if we close this issue for now?

Thanks for your contribution to the design of the SDK.

**Comment by GraceYBR** [comment] 2021-03-12 02:45
Hey @RichardCubic, I wanted to give you a quick update on this issue. At the moment we've got this enhancement in our internal backlog for the SDK. Our workflow at the moment is to actively work with Xero teams to make sure that new Enums are added to the SDK before they are published in the API. We will be closing this issue but still have it in our backlog to pick up. Thank you for your suggestion, we appreciate it!

**Closed by GraceYBR** 2021-03-12 02:45 UTC
Labels: OAuth 2.0, Status: In Discussion, Type: Enhancement
