### ISSUE TITLE
CreateInvoicesAsync  call producing activity records against the invoice's contact

### ISSUE THREAD

**Issue by mrfvintage** [XeroAPI/Xero-NetStandard#312] opened 2021-02-05 03:27 UTC
Bug: Xero.NetStandard.Oauth2
 - Version 3.13.1

**Describe the bug**
AccountingApi.CreateInvoicesAsync call results in new System Generated contact activity records against contacts with more than 1 contactperson.
Activity Text: "Additional contact person's email address changed from no value to secondCont@gmail.com."
![image](https://user-images.githubusercontent.com/1653980/106984482-69fe1c00-67b3-11eb-870a-bbb1a45432f4.png)

1. In front end GUI, go to a contact. Click EDIT and add a secondary contactperson ( firstname, lastname, email )
2. In the .NET application use the contact from step 1 in a CreateInvoicesAsync  call to create a new invoice
3. In front end GUI, go to the contact and inspect the activity records

**Expected behavior**
No new contact activity records. Only activity records should be against the invoice.

Was able to reproduce bug using UpdateOrCreateInvoicesAsync  method as well.

**Comment by jamie-hoffmann-xero** [comment] 2021-02-09 01:18
Hi @mrfvintage, unfortunately I am unable to reproduce the issue. I'd like to clarify the situation as it seems like some strange behaviour and may well be caused by something on the SDK side.

Here are the activity records I have after carrying out the steps:
![image](https://user-images.githubusercontent.com/74579854/107301724-274c8480-6ad0-11eb-9d57-65b01d34ece0.png)
("nobody" is the name of the contact I chose)

As you can see, I received a very similar activity record when I added the secondary contact details. Did you also receive an activity record when adding secondary contact details -- and if so, is that "System Generated" record _in addition_ to the one with your name on it?

**Comment by mrfvintage** [comment] 2021-02-09 01:37
Yes. System Generated is in addition to one with my name on it.

![image](https://user-images.githubusercontent.com/1653980/107303645-37159a00-6acb-11eb-8379-596e6a419d35.png)

**Comment by jamie-hoffmann-xero** [comment] 2021-02-09 02:40
Are you able to share the relevant bits of your code? Especially retrieving/constructing the Contact object and the call to `CreateInvoicesAsync`

**Comment by mrfvintage** [comment] 2021-02-09 02:58
Thanks for looking at this Jamie...
`
public static Invoice GenerateInvoiceObject(Contact contact, List<LineItem> lines)
        {
            var invoice = new Invoice()
            {
                Reference = "XeroAuth2Console",
                Type = Invoice.TypeEnum.ACCREC,
                Contact = contact,
                Date = DateTime.UtcNow,
                DueDate = DateTime.UtcNow.AddDays(30),
                LineItems = lines
            };
            return invoice;
        }

Guid gContactId = Guid.Parse("f39f00da-f314-4d9c-9c13-eb5bae15143d"); // mrf vintage

await CheckTokenCurrent();
var xeroToken = GetStoredToken();
string accessToken = xeroToken.AccessToken;
var AccountingApi = new AccountingApi();

var cResponse = await AccountingApi.GetContactAsync(accessToken, guidTenantID.ToString(), gContactId);
var customer = cResponse._Contacts[0];

var litem = new LineItem
            {
                Description = "line1Test",
                LineAmount = (decimal) 32.5
            };

var lineItems = new List<LineItem>();
lineItems.Add(litem);

// 1. Existing Invoice
//Invoice xeroInv;
//xeroInv = invoicesFromXero.FirstOrDefault(x => x.InvoiceNumber == "ORC1045");

// 2. New Invoice
Invoice xeroInv = GenerateInvoiceObject(customer,lineItems);

xeroInv.LineItems = lineItems;

await CheckTokenCurrent();
var xeroToken = GetStoredToken();

string accessToken = xeroToken.AccessToken;
var AccountingApi = new AccountingApi();

var listInv = new List<Invoice>();
listInv.Add(xeroInv);

var invoices = new Invoices();
invoices._Invoices = listInv;

var iResponse = await AccountingApi.CreateInvoicesAsync(accessToken, guidTenantID.ToString(), invoices);
`

**Comment by jamie-hoffmann-xero** [comment] 2021-02-09 03:52
Hey @mrfvintage, found a solution for you.

Basically what's happening is that the email address field is being set from your local variable `contact.ContactPersons[0].EmailAddress`. When you use the singular `GetContactAsync` endpoint, you get the entire available Contact model, including these details. This is why I couldn't reproduce the bug before -- I wasn't using this endpoint to retrieve my Contact object.

Not sure why the invoice endpoint sets this field. I can report this to the API team, but I should temper expectations: considering that it's pretty low-impact it may not be prioritised highly. 

However, there's an easy solution. For this use case, all we need to do is create a barebones Contact object with only the ContactID set:
```csharp
var contact = new Contact
{
    ContactID = Guid.Parse("12341234-1234-1234-1234-123412341234");
};
```

Let me know if you need any further help with this issue, otherwise I'll close it up in a few days. Thanks again for reporting :)

**Comment by mrfvintage** [comment] 2021-02-09 04:24
Thanks Jamie. 
I tested your workaround...  great outcome!
Invoice was created with the correct contact, and no additional "System Generated"  contact activity records.

**Closed** 2021-02-09 04:43 UTC
Labels: Status: Completed
