### ISSUE TITLE
Issue in Xero oAuth2 Authorization process 

### ISSUE THREAD

**Issue by rahulDev10** [XeroAPI/Xero-NetStandard#271] opened 2020-12-01 20:36 UTC
**Xero-NetStandard**
 - Xero .Net OAuth Client SDK

**Issue in Xero Authorization process**

We are using standard .NET 4.7 (not MVC)
I fam following the code from this repo: https://github.com/XeroAPI/Xero-NetStandard/tree/master/Xero.NetStandard.OAuth2Client

I can reach on the Login page using that code but having an issue while retrieving the token from the auth code sent by Xero.

when the code reaches the following line, the login page just keeps loading (trying to give access) and not returning anything 
var xeroToken = (XeroOAuth2Token)await client.RequestAccessTokenAsync(code);

(I've attached the screenshots)

Also, I tried using the following code which was in the original repo (the link above), but it gives me an error: XeroClient does not contain a definition for getConnections
List<Tenant> tenants = await client.GetConnections();

So I modified the code to use the following and that's where its not returning anything.
 var xeroToken = (XeroOAuth2Token)await client.RequestAccessTokenAsync(code);
List<Tenant> tenants = await client.GetConnectionsAsync(xeroToken);

Could you please help me solve this and point me in the right direction?

![Code](https://user-images.githubusercontent.com/75336025/100793956-c8d8a980-3481-11eb-8707-81b5b6de01da.png)
![XeroNotResponding](https://user-images.githubusercontent.com/75336025/100793978-cece8a80-3481-11eb-8200-1ba1e723d9cf.png)
![getConnections](https://user-images.githubusercontent.com/75336025/100793996-d42bd500-3481-11eb-992f-691b757e0b3e.png)

**Comment by jenksguo** [comment] 2020-12-02 03:05
Hi @rahulDev10, could you please provide a bit more context on your problem and also let us know your version of the OAuth2Client SDK version? 

The OA2 consent screen will get stuck if the callback url ( your /XeroAuthorizeAync endpoint) does not respond a 200 response. 

The more information you provide, the more we can help you with.

**Comment by rahulDev10** [comment] 2020-12-02 20:20
Hi @jenksguo, I've started working on moving our Xero authentication to OAuth2.

I am using the following SDK's for this project:
1. Xero.NetStandard.OAuth2 (version: 3.9.0)
2.Xero.NetStandard.OAuth2Client (version: 1.2.2)

The process:
I created a new class for XeroAuthorizationAuth2 and added 2 functions:
1. This sends the user to Xero the login page:
 public void XeroConnectAuth2()
        {

            XeroConfiguration xconfig = new XeroConfiguration();
            xconfig.ClientId = ConfigurationManager.AppSettings["XeroClientId"];
            xconfig.ClientSecret = ConfigurationManager.AppSettings["XeroClientSecret"];
            xconfig.CallbackUri = new Uri(ConfigurationManager.AppSettings["XeroCallbackUri"]); 
            xconfig.Scope = ConfigurationManager.AppSettings["XeroScope"];
            var client = new XeroClient(xconfig);
            HttpContext.Current.Response.Redirect(client.BuildLoginUri(), false);

        } 
2. Gets the code from Xero and retrieve the token from it;
        public async Task XeroAuthorizeAsync(string code)
        {
            XeroConfiguration xconfig = new XeroConfiguration();
            xconfig.ClientId = ConfigurationManager.AppSettings["XeroClientId"];
            xconfig.ClientSecret = ConfigurationManager.AppSettings["XeroClientSecret"];
            xconfig.CallbackUri = new Uri(ConfigurationManager.AppSettings["XeroCallbackUri"]); 
            xconfig.Scope = ConfigurationManager.AppSettings["XeroScope"];
            var client = new XeroClient(xconfig);

            var xeroToken = (XeroOAuth2Token)await client.RequestAccessTokenAsync(code);
            //from here you will need to access your Xero Tenants
            List<Tenant> tenants = await client.GetConnectionsAsync(xeroToken);
            // you will now have the tenant id and access token
            foreach (Tenant tenant in tenants)
            {
                // do something with your tenant and access token
                //client.AccessToken;
                //tenant.TenantId;
            }
        }

Our callback URL is our web form page when user click on Allow Access, Xero sends back the code and on Page load method of our webform, I use the following code to send the code to 2nd method(mentioned above)
               //oauth2_code is Code send back by Xero
                else if (oauth2_code != null)
                {
                    VegaSessionBLL.LogError(DateTime.UtcNow, "Logging - Start Authorisation", VegaSession.UserId, "OrgProfile", 
                   VegaSession.UserName, 1);
                    var xeroObject = new XeroObject(VegaDataHelpers.ConnectionString, VegaSession.UserId, VegaSession.UserName);
                    xeroObject.AuthorizeAuth2Async(oauth2_code, oauth2_state).Wait();
                }

But in the second method (XeroAuthorizeAsync), when the code reaches the following line to get the token from code, it just get stuck there, nothing happens
var xeroToken = (XeroOAuth2Token)await client.RequestAccessTokenAsync(code);


I hope it helps you understand the problem.

**Comment by rahulDev10** [comment] 2020-12-14 20:30
Hi @jenksguo, Is there any update on this?
The deadline to move from OAuth to OAuth2.0 is coming closer, I am a bit worried.

**Comment by jenksguo** [comment] 2020-12-15 00:30
Hi @rahulDev10, I understand you need some assistance urgently. 

The actual cutoff of OAuth 1.0a is end of March 2021, the December deadline is now a recommended time for all certified partner to move. 

So rest assure your existing connection and the ability of onboarding new connection will not be impacted for the next 3 months. 

We will assess your scenario and get back to you as soon as possible.

**Comment by jenksguo** [comment] 2020-12-15 00:32
Hi @rahulDev10, looked over your response again. There is till not enough information for us to help you unfortunately. Are you able to put a debugger breakpoint to see what is causing the exception? 

"var xeroToken = (XeroOAuth2Token)await client.RequestAccessTokenAsync(code);" 

This should return an xeroToken object with all of the token set information. You should not expect any UI changes. :-)

**Comment by rahulDev10** [comment] 2020-12-15 20:16
Hi @jenksguo like I said before that's where the problem is.

the below line of code doesn't return anything
"var xeroToken = (XeroOAuth2Token)await client.RequestAccessTokenAsync(code);" 

as soon as the below line is executed, Xero login page gets stuck in connecting... and doesn't return XeroObject.

I don't know what more information I can give

**Comment by jenksguo** [comment] 2020-12-15 22:47
Hi @rahulDev10, the xero login gets stuck because in your callback method there is no view displayed. 

We are waiting for an 200 response from your server to display the next callback page e.g. localhost:5000/callback must return a valid response. 

So the UI is as expected. 

Can you do a return of an empty view or a 200 response so the task gets completed and inspect the full callback url? 

This is the sample code that worked for us: 

![image](https://user-images.githubusercontent.com/41350731/102281767-a5365880-3f83-11eb-82a4-1d7f4d6940a4.png)

**Comment by rahulDev10** [comment] 2020-12-16 01:31
Hi @jenksguo our application uses Asp.net webforms, would that work with it?
Do you have any example that works with web forms?

**Comment by jenksguo** [comment] 2020-12-23 11:11
Hi @rahulDev10, sorry for the delay. 

I think you might have run into Web Form UI deadlocks using request token async the asynchronous method. 

This had been discussed in [another closed issue](https://github.com/XeroAPI/Xero-NetStandard/issues/111). 

You may want to try the following to force the UI program to run async method synchronously: 

first:
using System.Threading.Tasks;

for method returns an response (like an GET API call):
var response = Task.Run(async () => await AccountingApi.GetInvoicesAsync(xeroToken, TenantId)).Result;

for method returns void (like delete connections):
Task.Run(async () => await client.DeleteConnectionAsync(xeroToken, xeroToken.Tenants[0]));

Please let me know if this unlocks you from your development.

**Comment by alanb21** [comment] 2021-01-04 07:55
I have a similar problem.  I get the following error on the same line.

MissingMethodException: Method not found: 'System.Threading.Tasks.Task`1<IdentityModel.Client.TokenResponse> IdentityModel.Client.HttpClientTokenRequestExtensions.RequestAuthorizationCodeTokenAsync(System.Net.Http.HttpMessageInvoker, IdentityModel.Client.AuthorizationCodeTokenRequest, System.Threading.CancellationToken)'.

**Comment by alanb21** [comment] 2021-01-04 10:30
Hi,  

I'm in the process of setting up a new Xero instance so I have no choice but to use OAuth2.  I have the same problem using ASP.NET 4.8 where it gets stuck at:

var xeroToken = (XeroOAuth2Token)await client.RequestAccessTokenAsync(code);

We can't do anything until we have a solution for this.  Please help.

**Comment by OPCSJames** [comment] 2021-01-05 16:32
![image](https://user-images.githubusercontent.com/77016058/103671865-6a688480-4f73-11eb-8894-d71d994a8015.png)

Got the same issue today trying to update to OAuth2, it's stuck on that same line. Also using Web Forms like one person said above but added the MVC stuff anyway as I can't find any support for Web Forms....but still not working as of yet.

**Comment by alanb21** [comment] 2021-01-17 00:50
I found a solution that worked.

1. Use var response = Task.Run(async () => await AccountingApi.GetInvoicesAsync(xeroToken, TenantId)).Result; as per Jenksgua's comment.

2.,  Make sure you have <httpRuntime targetFramework="4.x"> under <system.web> in your Web.config file.  My exact line was:

 <httpRuntime targetFramework="4.8" maxRequestLength="20000" executionTimeout="36000"  />

**Comment by rahulDev10** [comment] 2021-01-19 22:46
Hi @jenksguo the issue with deadlock is resolved using your suggested code.
Now I got another question, do I still need to use PartnerConsumerKey and PartnerConsumerSecret with Auth 2 for using Xero API?

Also, do we need to change the way we are using Xero.Api.Core functions to push and get data from Xero using Auth2.0

**Comment by rahulDev10** [comment] 2021-01-21 23:53
Hi @jenksguo Also I am bit confused about refreshing access code. The documentation says access token express after 30 mins.

So I refresh the token using following method:
var newToken = Task.Run(async () => (XeroOAuth2Token)await client.RefreshAccessTokenAsync(xeroToken1)).Result;

My understanding is this, the newToken will have new access and refreshToken with expiry date 30 days from today's date. But its still returning old expiry date?
 
Could you please clarify this?

**Comment by rahulDev10** [comment] 2021-01-28 01:20
Hi, @jenksguo Could you please reply to above, it's bit urgent? Thanks

**Comment by AdamD92** [comment] 2021-02-05 14:54
We had an issue with the `client.RequestAccessTokenAsync(code)` method producing similar errors to the ones shown above for our webforms application.

When none of the above sections worked, we solved these issue by putting ` ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls11 | SecurityProtocolType.Tls12;` before making the calls to xero.

**Comment by folencao** [comment] 2021-02-28 12:51
We had the same error on our production server while it is ok on dev/stage server, finally the issue is `IdentityModel` package require >= 4.6.1 .NET Framework version but our production server has max 4.6.0 version, after we installed 4.8 .NET Framework runtime, the error gone.

**Comment by jenksguo** [comment] 2021-03-12 03:35
@rahulDev10 Hey sorry for getting back to you late. 

The OAuth 2.0 API calls requires different headers than OAuth 1.0a so you must tweak the httpClient to be able to use the old SDK. 

We have not changed the data model so you may use the models/classes from the old SDK. 

The consumerKey and consumerSecret are now called ClientID and ClientSecret.

**Comment by jenksguo** [comment] 2021-03-12 03:40
@rahulDev10 hey for token refresh I can explain more: 

access_token - always lives only for 30 minutes, past this you need to use refresh token and last working access token to get a new set

refresh_token - valid for 60 days, past this user must authorised the app again.  Once you initiated the refresh request, there is a grace period for 30 minutes on the refresh_token for you to retry as many times as you need until you have valid tokens.

**Comment by jenksguo** [comment] 2021-03-12 03:41
@rahulDev10 I take it that your original issue is gone now? Please confirm. 

@folencao Yes you are right, sorry, our SDK is on NetStandard 2.0 which supports 4.6.1+ only.

**Comment by rahulDev10** [comment] 2021-03-15 20:19
Hi  @jenksguo, yes it was resolved. Thanks

**Comment by jenksguo** [comment] 2021-03-15 20:57
Closing this issue. Please re-open if needed.

**Closed by jenksguo** 2021-03-15 20:57 UTC
Labels: Status: Help Wanted

**Comment by pmagique** [comment] 2021-11-15 21:03
Dear Xero team, I followed the discussion in this thread but couldn't fix the issue on our side. Basically, await methods RequestAccessTokenAsync and RefreshAccessTokenAsync work fin on dev local server. Moving the project on IIS, modifying callbacks were done. Where we stand is Xero Login page pops-up without any issue. Xero returns login code back to the callback method but the code fails at this point : RequestAccessTokenAsync.

Like @OPCSJames , error message shows "An error occurred while sending the request

Suggested solution by using "var xeroToken = Task.Run(async () => (XeroOAuth2Token)await client.RequestAccessTokenAsync(code)).Result;" was tried without any luck

[Exception: An error occurred while sending the request.]
   Xero.NetStandard.OAuth2.Client.<RequestAccessTokenAsync>d__8.MoveNext() +877
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +99
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
   NetStandardApp_net461.Controllers.<<Callback>b__0>d.MoveNext() in C:\ASPDavid\WebOmegaChem2021\WebOmegaChem2021\Controllers\AuthorizationController.cs:64

[AggregateException: One or more errors occurred.]
   System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions) +4323241
   System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification) +12866427
   System.Threading.Tasks.Task`1.get_Result() +33
   NetStandardApp_net461.Controllers.<Callback>d__1.MoveNext() in C:\ASPDavid\WebOmegaChem2021\WebOmegaChem2021\Controllers\AuthorizationController.cs:64
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +99
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
   System.Web.Mvc.Async.TaskAsyncActionDescriptor.EndExecute(IAsyncResult asyncResult) +97
   System.Web.Mvc.Async.<>c__DisplayClass8_0.<BeginInvokeAsynchronousActionMethod>b__1(IAsyncResult asyncResult) +17
   System.Web.Mvc.Async.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult) +10
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult) +32
   System.Web.Mvc.Async.<>c__DisplayClass11_0.<InvokeActionMethodFilterAsynchronouslyRecursive>b__0() +58
   System.Web.Mvc.Async.<>c__DisplayClass11_2.<InvokeActionMethodFilterAsynchronouslyRecursive>b__2() +228
   System.Web.Mvc.Async.<>c__DisplayClass7_0.<BeginInvokeActionMethodWithFilters>b__1(IAsyncResult asyncResult) +10
   System.Web.Mvc.Async.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult) +10
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult) +34
   System.Web.Mvc.Async.<>c__DisplayClass3_6.<BeginInvokeAction>b__4() +35
   System.Web.Mvc.Async.<>c__DisplayClass3_1.<BeginInvokeAction>b__1(IAsyncResult asyncResult) +100
   System.Web.Mvc.Async.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult) +10
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult) +27
   System.Web.Mvc.<>c.<BeginExecuteCore>b__152_1(IAsyncResult asyncResult, ExecuteCoreState innerState) +11
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +29
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult) +45
   System.Web.Mvc.<>c.<BeginExecute>b__151_2(IAsyncResult asyncResult, Controller controller) +13
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +22
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult) +26
   System.Web.Mvc.Controller.System.Web.Mvc.Async.IAsyncController.EndExecute(IAsyncResult asyncResult) +10
   System.Web.Mvc.<>c.<BeginProcessRequest>b__20_1(IAsyncResult asyncResult, ProcessRequestState innerState) +28
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +29
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult) +28
   System.Web.Mvc.MvcHandler.System.Web.IHttpAsyncHandler.EndProcessRequest(IAsyncResult result) +9
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +577
   System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step) +132
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +163

Regards

David
